# Generated by Django 2.0 on 2022-04-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220425_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariogestionabierta',
            options={'verbose_name': 'Usuarios de gestion abierta', 'verbose_name_plural': 'Usuario de gestion abierta'},
        ),
    ]
