# Generated by Django 3.1.13 on 2022-05-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20220425_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariogestionabierta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripcion del usuario'),
        ),
        migrations.AddField(
            model_name='usuariogestionabierta',
            name='objetivos',
            field=models.TextField(blank=True, null=True, verbose_name='objetivos del usuario'),
        ),
    ]
