# Generated by Django 3.1.13 on 2022-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20220517_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
