# Generated by Django 5.0 on 2026-02-03 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('CD', 'Mini CD'), ('VINYL', 'Mini Vinyl'), ('CUSTOM_BOOK', 'Custom Book')], max_length=20)),
                ('case_color', models.CharField(blank=True, max_length=50, null=True)),
                ('nfc_url', models.URLField(blank=True, help_text='URL for NFC/QR redirect', null=True)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='products/pdfs/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
