# Generated by Django 5.0 on 2026-02-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='department',
            field=models.CharField(blank=True, help_text='Department/State if outside Bogotá', max_length=100, null=True),
        ),
    ]
