# Generated by Django 2.0 on 2022-04-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, null=True)),
                ('descripcion', models.TextField()),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='gestion_abierta/informes/evidencias/')),
                ('url_evidencia', models.CharField(blank=True, max_length=500, null=True, verbose_name='url de evidencia')),
                ('fecha_informe', models.DateField(null=True)),
                ('estado', models.CharField(choices=[('Publicado', 'publicado'), ('Descartado', 'descartado'), ('Sin publicar', 'sin publicar')], default='Sin publicar', max_length=50, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.UsuarioGestionAbierta')),
            ],
        ),
    ]
