# Generated by Django 3.1.13 on 2022-05-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupGobiernoAbierto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='gestion_abierta/informes/evidencias/')),
            ],
        ),
    ]
