# Generated by Django 3.1.13 on 2022-06-17 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_abierta', '0002_backupgobiernoabierto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='gestion_abierta/informes/evidencias/', verbose_name='archivo'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='gestion_abierta/informes/archivos/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='informe',
            name='archivo',
            field=models.ManyToManyField(to='gestion_abierta.Archivo', verbose_name='evidencias'),
        ),
    ]
