# Generated by Django 3.1.13 on 2022-06-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0003_auto_20220617_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='archivo',
        ),
        migrations.AddField(
            model_name='informe',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_abierta.archivo', verbose_name='evidencias'),
        ),
    ]
