# Generated by Django 3.1.13 on 2022-06-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0004_auto_20220617_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='archivo',
        ),
    ]
