# Generated by Django 3.1.13 on 2022-06-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0005_remove_informe_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_abierta.informe', verbose_name='informe'),
        ),
    ]
