# Generated by Django 3.1.13 on 2022-06-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0007_auto_20220617_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseBuscada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(blank=True, max_length=200, null=True, verbose_name='frase buscada')),
                ('estado', models.BooleanField(default=False, verbose_name='aprobada')),
            ],
        ),
    ]
