# Generated by Django 3.1.13 on 2022-06-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0008_frasebuscada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasebuscada',
            name='frase',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='frase buscada'),
        ),
    ]
