# Generated by Django 3.1.13 on 2022-06-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0009_auto_20220620_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='frasebuscada',
            name='num_busqueda',
            field=models.PositiveBigIntegerField(default=1, verbose_name='numero de busquedas'),
        ),
    ]
