# Generated by Django 3.1.13 on 2022-06-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0010_frasebuscada_num_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='frasebuscada',
            name='color',
            field=models.CharField(blank=True, default='#DCFB8A', max_length=50, null=True, verbose_name='color de busqueda'),
        ),
    ]
