# Generated by Django 3.1.13 on 2022-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0011_frasebuscada_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='gestion_abierta/informes/ods/', verbose_name='imagen')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Objetivo de desarrollo sostenible',
                'verbose_name_plural': 'Objetivos de desarrollo sostenible',
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='ods',
            field=models.ManyToManyField(to='gestion_abierta.ODS', verbose_name='Objetivos de desarrollo sostenible'),
        ),
    ]
