# Generated by Django 3.1.13 on 2022-06-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0012_auto_20220622_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='gestion_abierta/informes/ods/', verbose_name='imagen'),
        ),
    ]
