# Generated by Django 3.1.13 on 2022-06-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0013_auto_20220622_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='ods',
            name='link_onu',
            field=models.URLField(blank=True, null=True, verbose_name='link de informacion de la ONU'),
        ),
    ]
