# Generated by Django 3.1.13 on 2022-07-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0014_ods_link_onu'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkEvidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('link_evidencia', models.URLField(blank=True, null=True, verbose_name='link de informacion de la ONU')),
            ],
            options={
                'verbose_name': 'Link de evidencia',
                'verbose_name_plural': 'Links de evidencias',
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='link_evidencias',
            field=models.ManyToManyField(to='gestion_abierta.LinkEvidencia', verbose_name='Links de evidencias'),
        ),
    ]
