# Generated by Django 3.1.13 on 2022-07-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0015_auto_20220710_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='link_evidencias',
            field=models.ManyToManyField(blank=True, to='gestion_abierta.LinkEvidencia', verbose_name='Links de evidencias'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='ods',
            field=models.ManyToManyField(blank=True, to='gestion_abierta.ODS', verbose_name='Objetivos de desarrollo sostenible'),
        ),
    ]
