# Generated by Django 3.1.13 on 2022-07-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_abierta', '0016_auto_20220710_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkevidencia',
            name='link_evidencia',
            field=models.URLField(blank=True, null=True, verbose_name='link de evidencia'),
        ),
        migrations.AlterField(
            model_name='linkevidencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='nombre'),
        ),
    ]
